<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.github.jhipster.test.LogbackRecorderTest" tests="16" skipped="0" failures="0" errors="0" timestamp="2019-02-19T21:14:12" hostname="K95VJ" time="0.043">
  <properties/>
  <testcase name="testTraceWithException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testOff" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testClear" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testDebug" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testError" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testTrace" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testInfo" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testWarn" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testErrorWithException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testCaptureException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testInfoWithException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testReleaseException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testOffWithException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testWarnWithException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testDebugWithException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testLogbackException" classname="io.github.jhipster.test.LogbackRecorderTest" time="0.038"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
