<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" tests="10" skipped="0" failures="0" errors="0" timestamp="2019-02-22T13:06:52" hostname="dev" time="1.658">
  <properties/>
  <testcase name="testSubmitRunnableWithException" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="1.42"/>
  <testcase name="testSubmitCallableWithException" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.028"/>
  <testcase name="testInitializingExecutor" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.095"/>
  <testcase name="testNonInitializingExecutor" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.002"/>
  <testcase name="testExecuteWithException" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.004"/>
  <testcase name="testSubmitRunnableWithoutException" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.015"/>
  <testcase name="testDisposableExecutor" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.071"/>
  <testcase name="testNonDisposableExecutor" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.001"/>
  <testcase name="testSubmitCallableWithoutException" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.015"/>
  <testcase name="testExecuteWithoutException" classname="fr.edjaz.socle.async.ExceptionHandlingAsyncTaskExecutorTest" time="0.003"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
